### ISSUE TITLE
Issue with PHPUnit and Clover

### ISSUE THREAD

**Issue by MrEssex** [paambaati/codeclimate-action#346]
**Describe the bug**
format-coverage throwing an UnhandledPromiseRejectionWarning as the formatter is trying to read files from an incorrect path.

**Version of `codeclimate-action` you're using**
`v2.5.7`

**Example links**
1. [Github Action with debug](https://github.com/MrEssex/simple-site/pull/5/checks?check_run_id=2622973553)
2. [PR Request with workflow php.yml](https://github.com/MrEssex/simple-site/pull/5/files)

**Expected behavior**
The test to run through without failing (PHP7.4, PHP8.0 known to fail due to composer package)

**Comment by osma** [comment]
I just hit the same issue.

I think the problem is that when using php-actions/phpunit to run the PHPUnit tests (as we are both doing), the tests will be executed within a container and the paths inside that container are different to those on the host machine (runner). On the host machine, the path to the app files is something like `/home/runner/work/<my-user>/<my-repo>` but in the phpunit container this is mounted as the `/app` volume. So for example in your case the cc-reporter tool is giving this error:

    Error: open /app/src/AbstractBase.php: no such file or directory

I bet that's because the coverage report, which has been run within the phpunit container, contains the filename `/app/src/AbstractBase.php` - but that path doesn't exist on the host/runner machine where cc-reporter is being run.

**Comment by osma** [comment]
I solved this with a `prefix` setting, like this:

```yaml
      with:
        prefix: /app
```

**Comment by MrEssex** [comment]
@osma 
Much appreciated for that mate,
Works a treat!
