### ISSUE TITLE
Can't read pyproject.toml errors

### ISSUE THREAD

**Issue by danyeaw** [paambaati/codeclimate-action#434]
**Describe the bug**
A couple of my repos are getting `Can't read 'pyproject.toml' without TOML support. Install with [toml] extra` errors on recent builds. I know pytest-cov recently updated, I'm not sure if this error is related to that update.

**Version of `codeclimate-action` you're using**
`v3.0.0`

**Example links**
Failing run: https://github.com/gaphor/generic/actions/runs/1310020693
Configuration: https://github.com/gaphor/generic/blob/afd62eaa532498b40b1995b436bfa0ec1ca35aa9/.github/workflows/build.yml

**Expected behavior**
Passing build.

**Additional context**

**Comment by paambaati** [comment]
@danyeaw This does look like an external dependency's issue. One quick way to confirm this is to modify your action to just run [these steps](https://docs.codeclimate.com/docs/configuring-test-coverage#quick-guide) and see if it works.

**Comment by danyeaw** [comment]
Running `pip install coverage[toml]` prior to running the codeclimate-action fixed the issue.

**Comment by uduwage-hobs** [comment]
@danyeaw thanks for your recommendation. `pip install coverage[toml]` worked. But I am curious what really caused this. I maintain a `pyproject.toml` that has requirement setup and nothing in our build process were change. But out of the blues this issue came up. I couldn't find any updates related to this on `pytest-cov`, `toml` etc. Do you know what dependency actually caused this?
