### ISSUE TITLE
Add "can't find this pattern" debug to getLocationLines

### ISSUE THREAD

**Issue by palfrey** [paambaati/codeclimate-action#678]
**Is your feature request related to a problem? Please describe.**
I've just spent about an hour debugging to finally figure out the `actions/download-artifact` didn't download where I thought it did, and so this code tried the smart way without telling me that's what I'd gotten wrong.

**Describe the solution you'd like**
If I specify a pattern in `coverageLocations` and it matches _nothing_, output a log line telling me this. TBH, maybe even throw an error (or have an option to do things this way)

**Describe alternatives you've considered**
Getting it right to begin with :)

**Comment by paambaati** [comment]
I'd like to avoid doing this if I can, because walking a list of files and checking for their existence is an expensive operation. Ideally this validation should exist outside of this action, as a separate step.

Here's a nice action that can do precisely that – https://github.com/marketplace/actions/file-existence
