### ISSUE TITLE
Does not run on macos-14

### ISSUE THREAD

**Issue by isaachinman** [paambaati/codeclimate-action#744]
This action does not successfully run on the hosted `macos-14` runners.

I get the following error:

```
/Users/runner/work/_actions/paambaati/codeclimate-action/v5.0.0/lib/utils.js:58
                throw new Error(`Download of '${url}' failed with response status code ${response.status}`);
Error: 🚨 CC Reporter download failed!
                      ^
Error: Download of 'https://codeclimate.com/downloads/test-reporter/test-reporter-latest-darwin-arm64' failed with response status code 403
    at /Users/runner/work/_actions/paambaati/codeclimate-action/v5.0.0/lib/utils.js:58:23
```

**Comment by isaachinman** [comment]
@paambaati Would love to see this fixed ASAP and am happy to help. Otherwise we will need to switch away to another CodeClimate action, or write our own. There are hosted darwin builds for OSX.

**Comment by isaachinman** [comment]
The key problem here is `arm64` vs `amd64`. Actually, I wonder if this is a CodeClimate limitation?

**Comment by paambaati** [comment]
It is indeed a CC limitation.

**Comment by rogerluan** [comment]
@paambaati I see the integration test code above, but it's actually failing instead of skipping, is this expected? E.g.:

<img width="882" alt="image" src="https://github.com/paambaati/codeclimate-action/assets/8419048/aeb39ad9-232a-476c-bb8e-7fc6c5102de5">

https://github.com/rogerluan/arkana/actions/runs/9431336943/job/25979873736

**Comment by paambaati** [comment]
@rogerluan This is expected, because CodeClimate does not publish ARM64 images — see https://github.com/codeclimate/test-reporter

I will make sure there’s a more obvious error message in the next release.

**Comment by rogerluan** [comment]
My bad, I thought the code above was a check in the runtime code that would print that message in case it was running on macOS, but it's just an integration test, not the actual code right 😅 

I guess I'll have to build for linux if I want to upload code coverage then 😬 since it looks like they're not interested in fixing that.

Thanks @paambaati

**Comment by paambaati** [comment]
Please upgrade to `v8.0.0` of this action and you should be able to see a more obvious error when using an unsupported environment.
