### ISSUE TITLE
Error: could not find any viable formatter, but the coverage report in clover format is there

### ISSUE THREAD

**Issue by limonte** [paambaati/codeclimate-action#93]
Link: https://github.com/sweetalert2/sweetalert2/runs/408048303?check_suite_focus=true

![image](https://user-images.githubusercontent.com/6059356/73108876-3f278980-3f0a-11ea-839c-a4f64b24b453.png)

There's the coverage report in `clover` format, you can verify in downloading the artifact:

![image](https://user-images.githubusercontent.com/6059356/73108913-59616780-3f0a-11ea-9792-a9a4177c0a09.png)

**Comment by paambaati** [comment]
@limonte That’s strange. Are you able to manually push coverage from the action?

**Comment by limonte** [comment]
@paambaati thanks for the response! what do you mean by "manually"?

**Comment by paambaati** [comment]
Here’s what I’d generally do in such cases —

1. Download the CodeClimate reporter and run tests locally and push the report myself manually.

2. If that works, then do the same thing via a shell script in an action step.

My guess is, the reporter can’t pick up your coverage output and is technically outside the scope of this action.

However, let me know if you can try this and see if it works. Otherwise, I’ll clone your repo locally and try that out myself tomorrow.

**Comment by limonte** [comment]
you're right, the issue is most probably on the cc-reporter, side. Closing this issue in favor of https://github.com/codeclimate/test-reporter/issues/417
